name: 🐧 Linux Builds
on: [push, pull_request]

# Global Settings
env:
  # Only used for the cache key. Increment version to force clean build.
  GODOT_BASE_BRANCH: 3.5
  GODOT_BIN: "./bin/godot.x11.opt.tools.64.mono"
  SCONSFLAGS: verbose=yes warnings=all werror=yes

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-linux
  cancel-in-progress: true

jobs:
  build-linux:
    runs-on: "ubuntu-20.04"
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Editor w/ Mono (target=release_debug, tools=yes)
            cache-name: linux-editor-mono
            target: release_debug
            tools: true
            sconsflags: module_mono_enabled=yes mono_static=yes mono_glue=no

          - name: Template w/ Mono (target=release, tools=no)
            cache-name: linux-template-mono
            target: release
            tools: false
            sconsflags: module_mono_enabled=yes mono_static=yes mono_glue=no debug_symbols=no

          - name: Template w/ Mono (target=release_debug, tools=no)
            cache-name: linux-template-debug-mono
            target: release_debug
            tools: false
            sconsflags: module_mono_enabled=yes mono_static=yes mono_glue=no

    steps:
      - uses: actions/checkout@v3

      - name: Linux dependencies
        shell: bash
        run: |
          # Azure repositories are not reliable, we need to prevent azure giving us packages.
          sudo rm -f /etc/apt/sources.list.d/*
          sudo cp -f misc/ci/sources.list /etc/apt/sources.list
          sudo apt-get update
          # The actual dependencies
          sudo apt-get install build-essential pkg-config libx11-dev libxcursor-dev \
              libxinerama-dev libgl1-mesa-dev libglu-dev libasound2-dev libpulse-dev \
              libdbus-1-dev libudev-dev libxi-dev libxrandr-dev yasm xvfb wget unzip

      - name: Setup Godot build cache
        uses: ./.github/actions/godot-cache
        with:
          cache-name: ${{ matrix.cache-name }}
        continue-on-error: true

      - name: Setup python and scons
        uses: ./.github/actions/godot-deps

      - name: Import certificates
        run: |
          curl -LO https://curl.haxx.se/ca/cacert.pem
          cert-sync --user cacert.pem

      - name: Compilation
        uses: ./.github/actions/godot-build
        with:
          sconsflags: ${{ env.SCONSFLAGS }} ${{ matrix.sconsflags }}
          platform: linuxbsd
          target: release_debug
          tools: true

      - name: Generate Mono glue code
        run: |
          DRI_PRIME=0 xvfb-run ${{ env.GODOT_BIN }} --generate-mono-glue modules/mono/glue || true

      - name: Compilation (mono_glue=yes)
        uses: ./.github/actions/godot-build
        with:
          sconsflags: ${{ env.SCONSFLAGS }} ${{ matrix.sconsflags }} mono_glue=yes
          platform: linuxbsd
          target: ${{ matrix.target }}
          tools: ${{ matrix.tools }}

      - name: Prepare artifact
        run: |
          strip bin/godot.*
          chmod +x bin/godot.*

      - name: Upload artifact
        uses: ./.github/actions/upload-artifact
        with:
          name: ${{ matrix.cache-name }}
